# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5aab52278cc59c611bac10aa5009ef949882e808a6d2954e4bebee08151c5ce847f6ea8b7bc1a4293c3f40969dba3f3c21f8dc3e5898c6ce5067cc2770c62760

test:
  secret_key_base: 328388dd9370d44f512e7780a08df5a76d674948396babca404f80a1d255a99a571fcf804359277b028325ee995bc2abd21862712a923cd51ae4f0209eddf6f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
